buttons:
    - name:           about
      type:           simple
      image:          "data/about.png"
      image_active:   "data/about_active.png"
      on_press:
      on_release:
        http_request: "http://127.0.0.1:8080/page/next"
    - name:           shutdown
      type:           simple
      image:          "data/power.png"
      image_active:   "data/power_active.png"
      on_release:
        actions: [
          Clear,
          Shutdown
        ]
    - name:           "shutdown red"
      type:           simple
      image:          "data/shutdown.png"
      image_active:   "data/shutdown_active.png"
      on_release:
        actions: [
          "Clear( 200, 10, 10 )",
#          Shutdown
        ]
    - name:           "shutdown blue"
      type:           simple
      image:          "data/shutdown.png"
      image_active:   "data/shutdown_active.png"
      on_release:
        actions: [
          "Clear( 10, 10, 200 )",
#          Shutdown
        ]
    - name:           "page prev"
      type:           simple
      image:          "data/left.png"
      image_active:   "data/left_active.png"
      on_release:
        actions: [
          "Clear( 80, 200, 200 )",
          "HttpGet(http://127.0.0.1:8080/page/prev)",
          "Test",
#          Shutdown
        ]
    - name:           "page next"
      type:           simple
      image:          "data/right.png"
      image_active:   "data/right_active.png"
      on_release:
        actions: [
          "Clear( 200, 200, 80 )",
          "HttpGet(http://127.0.0.1:8080/page/next)",
          "Test",
#          Shutdown
        ]

    - name:           "page 0"
      type:           simple
      image:          "data/page_0.png"
#      image_active:   "data/right_active.png"
      on_release:
        actions: [
          "HttpGet(http://127.0.0.1:8080/page/name/Page%200)",
        ]
    - name:           "page 1"
      type:           simple
      image:          "data/page_1.png"
#      image_active:   "data/right_active.png"
      on_release:
        actions: [
          "HttpGet(http://127.0.0.1:8080/page/name/Page%201)",
        ]
    - name:           "page 2"
      type:           simple
      image:          "data/page_2.png"
#      image_active:   "data/right_active.png"
      on_release:
        actions: [
          "HttpGet(http://127.0.0.1:8080/page/name/Page%202)",
        ]
    - name:           "page 3"
      type:           simple
      image:          "data/page_3.png"
#      image_active:   "data/right_active.png"
      on_release:
        actions: [
          "HttpGet(http://127.0.0.1:8080/page/name/Page%203)",
        ]
    - name:           "page 4"
      type:           simple
      image:          "data/page_4.png"
#      image_active:   "data/right_active.png"
      on_release:
        actions: [
          "HttpGet(http://127.0.0.1:8080/page/name/Page%204)",
        ]
pages:
    - name: default
      buttons: [
        shutdown,
        None,
        None,
        None,
        about,

        "page prev",
        None,
        about,
        None,
        "page next",

#        "shutdown blue",
        "page 0",
        "page 1",
        "page 2",
        "page 3",
        "page 4",
      ]
